CREATE TRIGGER T_ATUALIZAESTOQUE
AFTER INSERT ON APP.TB_PRODUTO_VENDA
REFERENCING NEW AS NOVOESTOQUE
FOR EACH ROW MODE DB2SQL
UPDATE APP.TB_PRODUTO SET PRO_ESTOQUE = (PRO_ESTOQUE - NOVOESTOQUE.PROVEN_QUANTIDADE)
WHERE PRO_CODIGO = NOVOESTOQUE.PROVEN_CODPRODUTO;

CREATE TRIGGER T_ATUALIZAESTOQUE2
AFTER DELETE ON APP.TB_PRODUTO_VENDA
REFERENCING OLD AS NOVOESTOQUE
FOR EACH ROW MODE DB2SQL
UPDATE APP.TB_PRODUTO SET PRO_ESTOQUE = (PRO_ESTOQUE + NOVOESTOQUE.PROVEN_QUANTIDADE)
WHERE PRO_CODIGO = NOVOESTOQUE.PROVEN_CODPRODUTO;