/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.table.DefaultTableModel;
import model.bean.Cliente;
import model.bean.Funcionario;
import model.bean.Produto;
import model.bean.ProdutoVenda;
import model.bean.Venda;
import model.dao.ProdutoDAO;
import model.dao.ProdutoVendaDAO;
import model.dao.VendaDAO;

/**
 *
 * @author lucas
 */
public class VendaView extends javax.swing.JFrame {

    /**
     * Creates new form VendaView
     */
    public VendaView() {
        initComponents();
        listarJTable();
        listarJTableProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVenda = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTItens = new javax.swing.JTable();
        bTListar = new javax.swing.JButton();
        jBCadastrar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtCliente = new javax.swing.JTextField();
        jTxtFuncionario = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTCliFun = new javax.swing.JTable();
        jFTxtData = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtProduto = new javax.swing.JTextField();
        jTxtQtd = new javax.swing.JTextField();
        jTxtValor = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTProduto = new javax.swing.JTable();
        jTxtIdPro = new javax.swing.JTextField();
        jTxtIdCli = new javax.swing.JTextField();
        jTxtIdFun = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTItensVenda = new javax.swing.JTable();
        jBInsert = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jBExcluirItem = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cliente", "Funcionario", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTVenda);

        jTItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTItens);

        bTListar.setText("Listar Vendas");
        bTListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTListarActionPerformed(evt);
            }
        });

        jBCadastrar.setText("Finalizar Venda");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir Venda");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBVoltar.setText("<< Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente:");

        jLabel2.setText("Funcionario:");

        jTxtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtClienteKeyTyped(evt);
            }
        });

        jTxtFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtFuncionarioKeyPressed(evt);
            }
        });

        jTCliFun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCliFun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCliFunMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTCliFun);

        try {
            jFTxtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Data:");

        jLabel4.setText("Produto:");

        jLabel5.setText("Quantidade:");

        jLabel6.setText("Valor:");

        jTProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProdutoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTProduto);

        jTItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Produto", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTItensVenda);

        jBInsert.setText("Adicionar Produto");
        jBInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInsertActionPerformed(evt);
            }
        });

        jBDelete.setText("Remover Produto");
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        jBExcluirItem.setText("Excluir Item Venda");
        jBExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jTxtIdPro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jTxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jFTxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTxtIdCli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTxtIdFun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTxtCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                                .addComponent(jTxtFuncionario)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTxtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(62, 62, 62)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jBDelete)
                                                .addComponent(jBInsert))
                                            .addGap(21, 21, 21)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bTListar)
                                .addGap(40, 40, 40)
                                .addComponent(jBCadastrar)
                                .addGap(40, 40, 40)
                                .addComponent(jBExcluir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBExcluirItem)
                                .addGap(77, 77, 77)
                                .addComponent(jBVoltar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtIdPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTxtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBInsert))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDelete))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTListar)
                    .addComponent(jBCadastrar)
                    .addComponent(jBExcluir)
                    .addComponent(jBVoltar)
                    .addComponent(jBExcluirItem))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInsertActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTItensVenda.getModel();
        
        model.addRow(new Object[]{
            jTxtIdPro.getText(),
            jTxtProduto.getText(),
            jTxtQtd.getText(),
            jTxtValor.getText(),});
        
        jTxtIdPro.setText("");
        jTxtProduto.setText("");
        jTxtQtd.setText("");
        jTxtValor.setText("");
    }//GEN-LAST:event_jBInsertActionPerformed

    private void jTProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProdutoMouseClicked
        // TODO add your handling code here:
        if (jTProduto.getSelectedRow() != -1) {

            jTxtIdPro.setText(jTProduto.getValueAt(jTProduto.getSelectedRow(), 0).toString());
            jTxtProduto.setText(jTProduto.getValueAt(jTProduto.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_jTProdutoMouseClicked

    private void jTCliFunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCliFunMouseClicked
        // TODO add your handling code here:
        if (jTCliFun.getSelectedRow() != -1) {

            if (fun) {
                jTxtIdFun.setText(jTCliFun.getValueAt(jTCliFun.getSelectedRow(), 0).toString());
                jTxtFuncionario.setText(jTCliFun.getValueAt(jTCliFun.getSelectedRow(), 1).toString());
            } else {
                jTxtIdCli.setText(jTCliFun.getValueAt(jTCliFun.getSelectedRow(), 0).toString());
                jTxtCliente.setText(jTCliFun.getValueAt(jTCliFun.getSelectedRow(), 1).toString());
            }
        }
    }//GEN-LAST:event_jTCliFunMouseClicked

    private void jTxtFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFuncionarioKeyPressed
        // TODO add your handling code here:
        listarJTableCliFun(jTxtFuncionario.getText(), false);
        fun = true;
    }//GEN-LAST:event_jTxtFuncionarioKeyPressed

    private void jTxtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtClienteKeyTyped
        // TODO add your handling code here:
        //listarJTableCliFun(jTxtFuncionario.getText(), true);
    }//GEN-LAST:event_jTxtClienteKeyTyped

    private void jTxtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtClienteKeyReleased
        // TODO add your handling code here:

        //String desc = jTxtFuncionario.getText();
        //listarJTableCliFun(jTxtFuncionario.getText(), true);
    }//GEN-LAST:event_jTxtClienteKeyReleased

    private void jTxtClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtClienteKeyPressed
        // TODO add your handling code here:

        //String desc = jTxtFuncionario.getText();
        listarJTableCliFun(jTxtCliente.getText(), true);
        fun = false;
    }//GEN-LAST:event_jTxtClienteKeyPressed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        HomeView homeview = new HomeView();
        homeview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:

        if (jTVenda.getSelectedRow() != -1) {

            Venda ven = new Venda();
            VendaDAO dao = new VendaDAO();

            ProdutoVenda proven = new ProdutoVenda();
            ProdutoVendaDAO pvdao = new ProdutoVendaDAO();

            ven.setCodigo((int) jTVenda.getValueAt(jTVenda.getSelectedRow(), 0));

            proven.setVenda(ven);
            pvdao.delete(proven);

            dao.delete(ven);

            DefaultTableModel modelo = (DefaultTableModel) jTItens.getModel();
            modelo.setRowCount(0);
            listarJTable();
            listarJTableProduto();
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        // TODO add your handling code here:

        Venda ven = new Venda();
        VendaDAO dao = new VendaDAO();

        String aux;
        int aux2;
        double aux3;

        int IDVen = dao.autoIncrement();
        ven.setCodigo(IDVen);
        ven.setData(jFTxtData.getText());

        Cliente cli = new Cliente();
        cli.setCodigo(Integer.parseInt(jTxtIdCli.getText()));

        Funcionario funcionario = new Funcionario();
        funcionario.setCodigo(Integer.parseInt(jTxtIdFun.getText()));

        ven.setCliente(cli);
        ven.setFuncionario(funcionario);

        dao.save(ven);

        for (int i = 0; i < jTItensVenda.getRowCount(); i++) {

            ProdutoVenda proven = new ProdutoVenda();
            ProdutoVendaDAO pvdao = new ProdutoVendaDAO();

            proven.setCodigo(pvdao.autoIncrement());

            Venda venp = new Venda();
            venp.setCodigo(IDVen);
            proven.setVenda(venp);

            Produto pro = new Produto();
            //pro.setCodigo((int)jTItensVenda.getModel().getValueAt(i, 0));
            aux = jTItensVenda.getModel().getValueAt(i, 0).toString();
            aux2 = Integer.parseInt(aux);
            pro.setCodigo(aux2);

            proven.setProduto(pro);

            //proven.setQuantidade((int)jTItensVenda.getModel().getValueAt(i, 2));
            aux = jTItensVenda.getModel().getValueAt(i, 2).toString();
            aux2 = Integer.parseInt(aux);
            proven.setQuantidade(aux2);

            //proven.setValor((double)jTItensVenda.getModel().getValueAt(i, 3));
            aux = jTItensVenda.getModel().getValueAt(i, 3).toString();
            aux3 = Double.parseDouble(aux);
            proven.setValor(aux3);

            pvdao.save(proven);
        }

        DefaultTableModel modelo = (DefaultTableModel) jTItensVenda.getModel();
        modelo.setRowCount(0);
        DefaultTableModel mod = (DefaultTableModel) jTCliFun.getModel();
        mod.setRowCount(0);
        jTxtCliente.setText("");
        jTxtFuncionario.setText("");
        jTxtIdCli.setText("");
        jTxtIdFun.setText("");
        jFTxtData.setText("");
        jTxtIdPro.setText("");
        jTxtProduto.setText("");
        jTxtQtd.setText("");
        jTxtValor.setText("");
        listarJTable();
        listarJTableProduto();
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void bTListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTListarActionPerformed
        // TODO add your handling code here:
        listarJTable();
    }//GEN-LAST:event_bTListarActionPerformed

    private void jTVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVendaMouseClicked
        // TODO add your handling code here:

        if (jTVenda.getSelectedRow() != -1) {

            listarJTableItens();
        }

    }//GEN-LAST:event_jTVendaMouseClicked

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTItensVenda.getModel();

        if (jTItensVenda.getSelectedRow() != -1) {

            modelo.removeRow(jTItensVenda.getSelectedRow());
            jTItensVenda.setModel(modelo);
        }
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jBExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirItemActionPerformed
        // TODO add your handling code here:        
        
        if (jTItens.getSelectedRow() != -1) {
            
            ProdutoVenda proven = new ProdutoVenda();
            ProdutoVendaDAO dao = new ProdutoVendaDAO();
            
            Produto pro = new Produto();
            
            pro.setDescricao(jTItens.getValueAt(jTItens.getSelectedRow(), 0).toString());
            
            proven.setProduto(pro);
            
            Venda ven = new Venda();
            
            ven.setCodigo((int)jTVenda.getValueAt(jTVenda.getSelectedRow(), 0));
            
            proven.setVenda(ven);
            
            proven.setQuantidade((int)jTItens.getValueAt(jTItens.getSelectedRow(), 1));
            
            dao.deleteIten(proven);
        }
        listarJTableItens();
        listarJTableProduto();
    }//GEN-LAST:event_jBExcluirItemActionPerformed

    boolean fun = false;

    public void listarJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jTVenda.getModel();

        modelo.setRowCount(0);
        VendaDAO dao = new VendaDAO();

        for (Venda v : dao.findAll()) {

            modelo.addRow(new Object[]{
                v.getCodigo(),
                v.getCliente().getNome(),
                v.getFuncionario().getNome(),
                v.getData(),});
        }
    }

    public void listarJTableProduto() {
        DefaultTableModel modelo = (DefaultTableModel) jTProduto.getModel();

        modelo.setRowCount(0);
        ProdutoDAO dao = new ProdutoDAO();

        for (Produto p : dao.findAll()) {

            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getDescricao(),
                p.getEstoque(),});
        }
    }

    public void listarJTableCliFun(String desc, boolean cli) {
        DefaultTableModel modelo = (DefaultTableModel) jTCliFun.getModel();

        modelo.setRowCount(0);
        VendaDAO dao = new VendaDAO();

        if (cli) {

            for (Venda v : dao.findClienteFuncionario(desc, cli)) {

                modelo.addRow(new Object[]{
                    v.getCliente().getCodigo(),
                    v.getCliente().getNome(),});
            }
        } else {

            for (Venda v : dao.findClienteFuncionario(desc, cli)) {

                modelo.addRow(new Object[]{
                    v.getFuncionario().getCodigo(),
                    v.getFuncionario().getNome(),});
            }
        }

    }

    public void listarJTableItens() {
        DefaultTableModel modelo = (DefaultTableModel) jTItens.getModel();

        int ID = (int) jTVenda.getValueAt(jTVenda.getSelectedRow(), 0);

        modelo.setRowCount(0);
        ProdutoVendaDAO dao = new ProdutoVendaDAO();

        for (ProdutoVenda pv : dao.find(ID)) {

            modelo.addRow(new Object[]{
                pv.getProduto().getDescricao(),
                pv.getQuantidade(),
                pv.getValor(),});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTListar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBExcluirItem;
    private javax.swing.JButton jBInsert;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JFormattedTextField jFTxtData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTCliFun;
    private javax.swing.JTable jTItens;
    private javax.swing.JTable jTItensVenda;
    private javax.swing.JTable jTProduto;
    private javax.swing.JTable jTVenda;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtCliente;
    private javax.swing.JTextField jTxtFuncionario;
    private javax.swing.JTextField jTxtIdCli;
    private javax.swing.JTextField jTxtIdFun;
    private javax.swing.JTextField jTxtIdPro;
    private javax.swing.JTextField jTxtProduto;
    private javax.swing.JTextField jTxtQtd;
    private javax.swing.JTextField jTxtValor;
    // End of variables declaration//GEN-END:variables
}
